### PR TITLE
ENH: Add slides to companion site

### PR DESCRIPTION
**Pull request by mmcky**
This PR adds slides to the companion site

### CODE REVIEW

**Comment by mmcky** [comment]
@jstac I didn't want to repeat `Chapter` in each button but I don't think the plain numbers look great. 

Screenshot 2024-01-18 at 9 02 46 pm

What about just using `Ch 1`, `Ch 2` for each cell?

**Comment by mmcky** [comment]
Screenshot 2024-01-18 at 9 07 01 pm

**Comment by mmcky** [comment]
@jstac ok I think this looks pretty good. Might ask @DrDrij how to align the blocks of buttons so they are the same width. 

Screenshot 2024-01-18 at 9 11 22 pm

What do you think?

**Comment by natashawatkins** [comment]
I'd suggest maybe the chapter titles as well? Maybe in the table format without icons? (Examples are in `elements.html`)

image

**Comment by DrDrij** [comment]
I like @natashawatkins idea to show the chapter titles. @mmcky Here is a preview and the HTML markup is underneath (copy/paste).

image


```
            <section>
                <header class="major">
                    <h2>Chapters</h2>
                </header>	
                <div class="table-wrapper">
                    <table class="alt" style="width:100%;">
                        <tbody>
                            <tr>
                                <td>Chapter 0</td>
                                <td><a href="https://github.com/QuantEcon/book-dp1/raw/main/slides/ch_0.pdf">Preface and Overview</a></td>
                            </tr>
                            <tr>
                                <td>Chapter 1</td>
                                <td><a href="https://github.com/QuantEcon/book-dp1/raw/main/slides/ch_1.pdf">Introduction</a></td>
                            </tr>
                            <tr>
                                <td>Chapter 2</td>
                                <td><a href="https://github.com/QuantEcon/book-dp1/raw/main/slides/ch_2.pdf">Operators and Fixed Points</a></td>
                            </tr>
                            <tr>
                                <td>Chapter 3</td>
                                <td><a href="https://github.com/QuantEcon/book-dp1/raw/main/slides/ch_3.pdf">Markov Dynamics</a></td>
                            </tr>
                            <tr>
                                <td>Chapter 4</td>
                                <td><a href="https://github.com/QuantEcon/book-dp1/raw/main/slides/ch_4.pdf">Optimal Stopping</a></td>
                            </tr>
                            <tr>
                                <td>Chapter 5</td>
                                <td><a href="https://github.com/QuantEcon/book-dp1/raw/main/slides/ch_5.pdf">Markov Decision Processes</a></td>
                            </tr>
                            <tr>
                                <td>Chapter 6</td>
                                <td><a href="https://github.com/QuantEcon/book-dp1/raw/main/slides/ch_6.pdf">Stochastic Discounting</a></td>
                            </tr>
                            <tr>
                                <td>Chapter 7</td>
                                <td><a href="https://github.com/QuantEcon/book-dp1/raw/main/slides/ch_7.pdf">Valuation</a></td>
                            </tr>
                            <tr>
                                <td>Chapter 8</td>
                                <td><a href="https://github.com/QuantEcon/book-dp1/raw/main/slides/ch_8.pdf">Recursive Decision Processes</a></td>
                            </tr>
                            <tr>
                                <td>Chapter 9</td>
                                <td><a href="https://github.com/QuantEcon/book-dp1/raw/main/slides/ch_9.pdf">Abstract Dynamic Programming</a></td>
                            </tr>
                            <tr>
                                <td>Chapter 10</td>
                                <td><a href="https://github.com/QuantEcon/book-dp1/raw/main/slides/ch_10.pdf">Continuous Time</a></td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </section>
```

**Comment by mmcky** [comment]
thanks @DrDrij @natashawatkins

**Comment by mmcky** [comment]
@jstac I like the suggestions from @natashawatkins and @DrDrij 

I have committed the following update

Screenshot 2024-01-19 at 1 41 59 pm

**Comment by mmcky** [comment]
@DrDrij any way to make the first column `centered` text?

**Comment by DrDrij** [comment]
Sorry I didn't get a response to you in time @mmcky. 

`<td style="text-align:center;">Chapter 0</td>`

**Pull request merged**
